### ISSUE TITLE
Filter doesnt work immediately

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#11] opened 2020-07-14 10:13 UTC
## Behavior
I apply the filter(year) and save, but it does not happen. I try again, then it shows the previous filtered result

## Expected Result
It immediately shows the result of the filter

## reproduce
1. Open filter
2. Unbutton all year besides the freshman
3. Still show all

**Comment by phooning** [comment] 2020-07-17 03:06
Duplicate of #2

**Closed as completed by phooning** 2020-07-17 03:06 UTC
