### ISSUE TITLE
Forgot password is broken

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#13] opened 2020-07-14 23:47 UTC
![Screenshot_20200715-084518_Pop](https://user-images.githubusercontent.com/46998867/87487037-987da380-c677-11ea-8d9b-62fa40342c3d.jpg)

## Behavior

Its keep on saying supply your email and doesnt progress. Also, I would change the email needs to be supplied to "Please write your email address."
Beta
Galaxy note 9
Build 1.670001

**Comment by phooning** [comment] 2020-07-15 01:22
Duplicate of #5, added error enhancement detail to #5

**Closed as completed by phooning** 2020-07-15 01:22 UTC
